Repository jenkinsci/stashnotifier-plugin, pull requests merged in 2023-08, with the labels that each got.

#328 Use logger instead of build log
  src/main/java/org/jenkinsci/plugins/stashNotifier/DefaultApacheHttpNotifier.java
Labels: enhancement

#326 Remove deprecated 'java.level' and .travis.yml
  .travis.yml
Labels: internal

#345 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: internal

#339 Update hamcrest
  pom.xml
Labels: dependencies

#347 Modernize Tooling and Jenkins to 2.387.3
  pom.xml
  src/test/java/org/jenkinsci/plugins/stashNotifier/StashNotifierTest.java
Labels: dependencies, internal

#348 Logging Enhancements
  src/main/java/org/jenkinsci/plugins/stashNotifier/DefaultApacheHttpNotifier.java
  src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java
Labels: enhancement

#349 Build on JDK 21
  Jenkinsfile
Labels: internal

#351 Add plugin developer team to CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog
